[package]
name = "svg_report"
version = "0.1.0"
edition = "2021"

[dependencies]
printpdf = "0.7.0"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"